language: python
sudo: false

python:
- '3.5'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_install:
- openssl aes-256-cbc -K $encrypted_6038fd128472_key -iv $encrypted_6038fd128472_iv
  -in private.tar.enc -out private.tar -d

install:
- pip install -r requirements.txt
- wget -q https://github.com/Cruel/3dstex/releases/download/1.1/3dstex-linux-x64
- wget -q $TITLEKEYSURL -O encTitleKeys.bin
- wget -q $PREVCACHEURL -O cache.tar.gz
- chmod +x 3dstex-linux-x64
- mkdir -p cache
- tar -xaf cache.tar.gz -C cache

script:
- "./gen_cache.py -i cache"
- "./3dstex-linux-x64 -bro etc1 images/*.png"

before_deploy:
- export RELEASE_FILENAME=cache-$TRAVIS_TAG
- tar -czf $RELEASE_FILENAME-jpg.tar.gz data.json images/*.jpg
- tar -czf $RELEASE_FILENAME-png.tar.gz data.json images/*.png
- tar -czf $RELEASE_FILENAME-etc1.tar.gz data.json images/*.bin

branches:
  only:
  - "/^r.*/"

deploy:
  provider: releases
  api_key:
    secure: muKPjoab9eStD7eIdcURSRkvuU7N2Bqkt6b6/Xd1BB2zd5VOezi5zH9yE2/wbuXuoksLMT8dGrvEmMuyLaKTj+WJqtHqupZUXsyMElL+9wxlq8V08z6bpY9uvUHGjMPdouu4htuSqlrYz135pig7IEj02ubaYPY98VxKSCpbcEGrRDOnWw8qbWpa4xqEfXdgp0q65MTng/0wLtp9DjHOBxc77DWhgC76erihfuv19YLtgNTqLLGapft3Dqvo51gjQ0doNU6xZdNkfZFKzqWE05sIVA3G/q+4ADe/T2+g+WJrJePXSOmg9FleGpGAK7xqbV4S23D/kjlTV7DoQ8LmPvdVDdnjtecma/2kkQadaoYWcq5cLfiuFgNipViu/jFx0Dikd8Z1h6cM5dmiWDckWxZ+iX1GnV5XOZVN8vSuSEQHm1Mrg1sFT2KMjPIEry/qEBIzI4MbSo2woownAYJOUG/K6LjgM5nXoBdxqZ95WS9SzWBvQaHSW8FYrPVNIBLoQlnrZuzKoRN8yOYNxMzmM9fEKyvggs7T5Yb3EmpczQfM/N6XRcrJrjrUkWPCwHHmZ+iANT39OX6LkbyHEL4lDBaTWXhSAaqNu/nYFajAG8nnci+tmPSdWPuUvKdS1uZoqJo+b+sT29PuqLdzmM3iM+KTuhHFRk55sl7XzhpTBbE=
  file:
    - $RELEASE_FILENAME-jpg.tar.gz
    - $RELEASE_FILENAME-png.tar.gz
    - $RELEASE_FILENAME-etc1.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: Repo3DS/shop-cache
