language: python
sudo: false

python:
- '3.5'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

before_install:
- openssl aes-256-cbc -K $encrypted_6038fd128472_key -iv $encrypted_6038fd128472_iv -in private.tar.enc -out private.tar -d
- tar xf private.tar

install:
- pip install -r requirements.txt
- wget -q https://github.com/Cruel/3dstex/releases/download/1.1/3dstex-linux-x64
- wget -q $TITLEKEYSURL -O encTitleKeys.bin
- wget -q $PREVCACHEURL -O cache.tar.gz
- chmod +x 3dstex-linux-x64
- mkdir -p cache
- tar -xaf cache.tar.gz -C cache

script:
- "./gen_cache.py -i cache"
- "./3dstex-linux-x64 -bro etc1 images/*.png"

before_deploy:
- export RELEASE_FILENAME=cache-$TRAVIS_TAG
- tar -czf $RELEASE_FILENAME-jpg.tar.gz data.json images/*.jpg
- tar -czf $RELEASE_FILENAME-png.tar.gz data.json images/*.png
- tar -czf $RELEASE_FILENAME-etc1.tar.gz data.json images/*.bin

branches:
  only:
  - "/^r.*/"

deploy:
  provider: releases
  api_key:
    secure: QrEQzXPVttiZyCsE9s0JkbykAvBCSE5asSq+/dfuXpQ5Wy3ivTezDtDWbY6jAo6V0ChydqYwW2bpRuCi8dw+BEPnmuhZbL70xqxTHgNUQgw9KWdQV7M56BUwT2Wa5m7tEqJcn1US/lf0/0ss/PSN8SU8uPfZAM+x1URelmHSy6d5pMycXksg9mtwkcLIXMO+8s/f00aT1A5LbmfFr8IRj6A9es7yrSgAu0N3Y9fbW1hUuogz7mOqH6f/XdX/CKgLHJk0jlruaauQ0/+w9DuGivaqCKCYLo11RbkVfdEAB/4JT6NVIdX3+D6p/6nLn5S+a1I8swVunKGs8291RqntEIJwRV/hywAA9Ny9ftw3bcpIv/gk7+fMBROZpne0JZcsX9+W2uoA+wc3tHrIXd0e0lxsvELm5oPFoG50wtlXzH6mP/Ew54YLGlzBxhYptEmWeIT9YXkINhRqtG9CBtzi+zUM3wiE/q1kGVVq1vUV1ByxrQGI2Gs4e4Q2MxKqzaommi6OwIQFRD4XAvPd3+KJTmvTN+/Ze5MHzJUcemrJWHxfFNpRbE532dZ7lKCjWcfUuNc9eE43vIT7HaHC9yXPmgxNhXCK/oT99rHcGWbWNMSvVitjSpeanfmuzJx3hG1S5mx6TJ1aAZejZZuOJEzumvoDtSFY8fs0hHSBSyITm+I=
  file:
    - $RELEASE_FILENAME-jpg.tar.gz
    - $RELEASE_FILENAME-png.tar.gz
    - $RELEASE_FILENAME-etc1.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: altCache/feature-cache
